// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whjuffaxazbhjeqisoyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoanVmZmF4YXpiaGplcWlzb3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjY4MzYsImV4cCI6MjA1OTk0MjgzNn0.PY6wwgETD9N_uIRo1ct5yTBB6Tfl3ho8qhEimWJZrBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);